import { useEffect } from 'react';
import { useSelector, useDispatch, shallowEqual } from 'react-redux';
import type { NextPage, GetServerSidePropsResult } from 'next';
import Head from 'next/head';

import { StoreState, wrapper } from 'store';
import { setCount } from 'store/modules/count';
// import { serverRenderClock, startClock } from 'store/modules/tick';

import Page from 'components/Page';

import styles, { container, main } from './index.styled';

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async (ctx): Promise<GetServerSidePropsResult<any>> => {
      try {
        // const { serverRenderClock } = mapDispatchToProps(store.dispatch);
        await store.dispatch(setCount(1231));
      } catch (err) {}

      return {
        props: {}
      };
    }
);

const Home: NextPage = () => {
  const state =  useSelector((state: StoreState) => ({
    ...state,
  }), shallowEqual);
  // const dispatch = useDispatch();
  // useEffect(() => {
  //   const timer: any = dispatch(setCount(1));
    
  //   return () => {
  //     clearInterval(timer);
  //   }
  // }, [dispatch]);
  console.log('count', state);
  return (
    <div className={container.className}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={main.className}>
        <h1>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p>
          Get started by editing <code>pages/index.js</code>
        </p>

        <div>
          <a href='https://nextjs.org/docs'>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn'>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href='https://github.com/vercel/next.js/tree/master/examples'>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'>
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
        {/* <Page title="Index Page" linkTo="/other" /> */}
      </main>

      <footer>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'>
          Powered by{' '}
        </a>
      </footer>

      {container.styles}
      {main.styles}
      <style jsx>{styles}</style>
    </div>
  );
};

export default Home;
